"""Reviewable business plans over existing services. One plan, one transaction."""

from decimal import Decimal, InvalidOperation
import hashlib
import json
import math
from typing import Literal

from fastapi import HTTPException
from pydantic import Field
from sqlalchemy import select

from document_pipeline_api.models import (
    DataRowRecord,
    DataTableRecord,
    DataViewRecord,
    TaskRecord,
    AssistantToolCall,
    AssistantRun,
    AssistantMessage,
)
from document_pipeline_api.services.assistant_analysis import Strict
from document_pipeline_api.services import data_tables, templates, data_rows, data_views, tasks


class Operation(Strict):
    kind: Literal[
        "update_rows",
        "increment_rows",
        "add_rows",
        "delete_rows",
        "tasks",
        "split_table",
        "add_column",
        "rename_table",
        "create_table",
    ]
    table_id: str | None = None
    row_ids: list[int] = Field(default_factory=list, max_length=200, description="要修改的真实记录编号，例如 [13,14]。不是字段序号；从 read_data_rows 的 row_id 读取。all_in_scope=true 时为空数组。")
    all_in_scope: bool = Field(default=False, description="用户明确要求修改当前授权范围的全部记录时设为 true，省略 row_ids；服务端确定记录和数量。指定某几条记录时用真实 row_ids，不可与本项同时使用。")
    changes: dict[str, str | int | float | bool | None] = Field(
        default_factory=dict, max_length=20,
        description="update_rows 表示设为指定值；increment_rows 表示数值增量，例如金额加1用 {amount: 1}，减1用 {amount: -1}。不能把加1写成 update_rows。",
    )
    rows: list[dict[str, str | int | float | bool | None]] = Field(
        default_factory=list, max_length=50, description="只用于 add_rows 新增记录；修改已有记录禁止使用 rows，请使用 row_ids。"
    )
    template_id: str | None = None
    # Old saved data plans included these empty template-only slots.
    template: None = Field(default=None, exclude=True)
    version: None = Field(default=None, exclude=True)
    task_ids: list[str] = Field(default_factory=list, max_length=50)
    action: Literal["pause", "resume", "retry", "cancel"] | None = None
    name: str | None = Field(default=None, max_length=128)
    field_key: str | None = None
    by_file: bool = False
    section: Literal["header", "item"] = "item"


class Plan(Strict):
    title: str = Field(min_length=1, max_length=120)
    operations: list[Operation] = Field(min_length=1, max_length=12)


class UndoPlan(Plan):
    # Generated by the server from a <=500-row executed preview, never exposed
    # as a larger write schema to the model.
    operations: list[Operation] = Field(min_length=1, max_length=500)


class Undo(Strict):
    tool_id: str


CAPABILITY = {
    "update_rows": "data",
    "increment_rows": "data",
    "add_rows": "data",
    "delete_rows": "data",
    "tasks": "tasks",
    "split_table": "organize",
    "add_column": "organize",
    "rename_table": "organize",
    "create_table": "organize",
}
LABELS = {
    "update_rows": "修改数据",
    "increment_rows": "调整数值",
    "add_rows": "新增记录",
    "delete_rows": "删除记录",
    "tasks": "任务操作",
    "split_table": "创建分 Sheet",
    "add_column": "新增附加列",
    "rename_table": "重命名表",
    "create_table": "创建数据表",
}


def digest(value):
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, ensure_ascii=False, default=str).encode()
    ).hexdigest()


def guard(session, kind, identifier):
    if kind == "view":
        view = session.get(DataViewRecord, identifier)
        return None if not view else digest([view.table_id, view.field_key, view.field_value_json])
    if kind == "scope":
        selection = json.loads(identifier)
        from document_pipeline_api.services.assistant_tools import Context

        return digest(scope_rows(session, Context.model_validate(selection["context"]), selection["table_id"]))
    if kind == "row":
        row = session.get(DataRowRecord, int(identifier))
        return None if not row else digest([row.table_id, row.row_version, row.row_json])
    if kind == "table":
        table = session.get(DataTableRecord, identifier)
        return (
            None
            if not table
            else digest(
                [table.name, [c.model_dump() for c in data_tables.table_columns(session, table)]]
            )
        )
    if kind == "template":
        return digest(templates.get_template(session, identifier).model_dump())
    if kind == "membership":
        return digest(
            [
                (r.id, r.row_version, r.row_json)
                for r in session.scalars(
                    select(DataRowRecord)
                    .where(DataRowRecord.table_id == identifier)
                    .order_by(DataRowRecord.id)
                )
            ]
        )
    task = session.get(TaskRecord, identifier)
    return (
        None
        if not task
        else digest(
            [task.status, task.updated_at, task.model_profile_id, task.model_profile_version]
        )
    )


def entire_table(context, table_id):
    if context.table_id == table_id and (
        context.row_ids is not None or context.search or context.view_id or context.task_id
    ):
        raise HTTPException(403, "此操作影响整张表；请在资料选择器中明确选择整张表后再提出。")


def increment_value(value, delta, label):
    if isinstance(value, bool) or isinstance(delta, bool) or value is None:
        raise HTTPException(422, f"「{label}」不是有效数值，不能增加或减少；请先核对该记录。")
    if not isinstance(delta, (int, float)):
        raise HTTPException(422, f"「{label}」的增量必须是数值。")
    try:
        original = Decimal(str(value).replace(",", "").strip())
        change = Decimal(str(delta))
        result = original + change
        if not original.is_finite() or not change.is_finite() or not math.isfinite(float(result)):
            raise InvalidOperation
        return int(result) if result == result.to_integral_value() else float(result)
    except (InvalidOperation, ValueError, OverflowError) as error:
        raise HTTPException(422, f"「{label}」不是有效数值，不能增加或减少；请先核对该记录。") from error


def scope_rows(session, context, table_id):
    from document_pipeline_api.services.assistant_tools import scoped_analysis
    from document_pipeline_api.services.assistant_analysis import AnalysisRequest, analyze

    result = analyze(session, scoped_analysis(session, context, AnalysisRequest(table_id=table_id, records=True, limit=201)))
    if result["source"]["row_count"] > 200:
        raise HTTPException(422, "当前范围超过 200 条记录，请先选择或筛选需要修改的记录后分批处理。")
    if not result["rows"]:
        raise HTTPException(422, "当前范围没有可修改的记录。")
    return result["rows"]


def preview_plan(session, context, body: Plan):
    from document_pipeline_api.services.assistant_tools import (
        permitted,
        require_capability,
        change_preview,
        Changes,
        ensure_row_scope,
    )

    items, guards, changed = [], {}, {}

    def watch(kind, identifier):
        guards[f"{kind}:{identifier}"] = guard(session, kind, identifier)

    for op in body.operations:
        require_capability(context, CAPABILITY[op.kind])
        item = {
            "operation": op.model_dump(mode="json"),
            "label": LABELS[op.kind],
            "affected": [],
            "before": None,
            "after": None,
        }
        if op.kind in {
            "update_rows",
            "increment_rows",
            "add_rows",
            "delete_rows",
            "split_table",
            "add_column",
            "rename_table",
        }:
            permitted(context, "table", op.table_id)
            table = session.get(DataTableRecord, op.table_id)
            if table is None:
                raise HTTPException(404, "表已不存在。")
            item["name"] = table.name
            watch("table", table.id)
            if context.table_id == table.id and context.view_id:
                watch("view", context.view_id)
            columns = {c.key: c for c in data_tables.table_columns(session, table)}
            item["columns"] = {k: c.label for k, c in columns.items()}
            root_ids = op.row_ids
            if op.all_in_scope:
                if op.kind not in {"update_rows", "increment_rows"} or op.row_ids:
                    raise HTTPException(422, "全部范围仅用于记录修改，不能同时指定记录 ID。")
                selected = scope_rows(session, context, op.table_id)
                root_ids = [row["row_id"] for row in selected]
                selection = json.dumps({"context": context.model_dump(exclude_none=True), "table_id": op.table_id}, sort_keys=True, ensure_ascii=False)
                watch("scope", selection)
                item["root_ids"] = root_ids
            if op.kind in {"update_rows", "increment_rows", "delete_rows"} and not root_ids:
                raise HTTPException(422, "需要明确指定记录 ID；用户要求当前范围全部记录时使用 all_in_scope=true，否则请先查询记录。")
            if op.kind in {"update_rows", "increment_rows"}:
                if not op.changes:
                    raise HTTPException(422, "没有提出字段变更。")
                for row_id in dict.fromkeys(root_ids):
                    changes = op.changes
                    if op.kind == "increment_rows":
                        ensure_row_scope(session, context, op.table_id, row_id)
                        current = json.loads(session.get(DataRowRecord, row_id).row_json)
                        changes = {}
                        for key, delta in op.changes.items():
                            if key not in columns or columns[key].value_type != "number":
                                raise HTTPException(422, "增加或减少只支持数值字段；请核对字段名称和类型。")
                            changes[key] = increment_value(current.get(key), delta, columns[key].label)
                    preview = change_preview(
                        session,
                        context,
                        Changes(table_id=op.table_id, row_id=row_id, changes=changes),
                    )
                    for row in preview["affected"]:
                        for key, value in row["after"].items():
                            identity = (row["row_id"], key)
                            if identity in changed and changed[identity] != value:
                                raise HTTPException(
                                    422,
                                    "同一公共字段被安排了互相冲突的修改，请合并为明确的一次变更。",
                                )
                            changed[identity] = value
                        watch("row", row["row_id"])
                        existing = next((r for r in item["affected"] if r["row_id"] == row["row_id"]), None)
                        if existing is None:
                            item["affected"].append(row)
                        else:
                            existing["before"].update(row["before"])
                            existing["after"].update(row["after"])
            elif op.kind == "delete_rows":
                for row_id in dict.fromkeys(root_ids):
                    ensure_row_scope(session, context, op.table_id, row_id)
                    row = session.get(DataRowRecord, row_id)
                    watch("row", row_id)
                    item["affected"].append(
                        {"row_id": row.id, "before": json.loads(row.row_json), "after": None}
                    )
                item["note"] = "删除记录及该行修订，不提供一键撤销；原件和任务仍保留。"
            else:
                entire_table(context, op.table_id)
                if op.kind == "add_rows":
                    if not op.rows or any(
                        any(key not in columns for key in row) for row in op.rows
                    ):
                        raise HTTPException(422, "新增记录不能为空或包含未知字段。")
                    item["after"] = op.rows
                elif op.kind in {"rename_table", "add_column"}:
                    if not op.name or not op.name.strip():
                        raise HTTPException(422, "名称不能为空。")
                    item["before"] = table.name if op.kind == "rename_table" else None
                    item["after"] = op.name
                else:
                    if not op.by_file and op.field_key not in columns:
                        raise HTTPException(422, "分组字段不存在。")
                    watch("membership", op.table_id)
                    item["after"] = (
                        "按文件分组"
                        if op.by_file
                        else "按 " + columns[op.field_key].label + " 分组"
                    )
        elif op.kind == "create_table":
            permitted(context, "template", op.template_id)
            current = templates.get_template(session, op.template_id)
            watch("template", current.id)
            item["name"] = current.name
            item["before"] = current.model_dump(mode="json")
            if not op.name:
                raise HTTPException(422, "需要表名称。")
            item["after"] = op.name
        else:
            if not op.task_ids or op.action is None:
                raise HTTPException(422, "需要指定任务和操作。")
            item["name"] = "批量任务"
            for identifier in dict.fromkeys(op.task_ids):
                permitted(context, "task", identifier)
                task = session.get(TaskRecord, identifier)
                if not task:
                    raise HTTPException(404, "任务已不存在。")
                from document_pipeline_api.domain.tasks import TaskState, TaskStatus

                target = {
                    "pause": TaskStatus.PAUSED,
                    "cancel": TaskStatus.CANCELLED,
                    "resume": TaskStatus.QUEUED,
                    "retry": TaskStatus.QUEUED,
                }[op.action]
                try:
                    if op.action == "resume" and task.status != TaskStatus.PAUSED.value:
                        raise ValueError("只有暂停的任务可以恢复。")
                    TaskState(status=TaskStatus(task.status)).transition_to(target)
                except Exception as error:
                    raise HTTPException(
                        409, f"任务「{task.filename}」当前状态不能执行 {op.action}。"
                    ) from error
                watch("task", identifier)
                item["affected"].append(
                    {
                        "task_id": identifier,
                        "name": task.filename,
                        "before": task.status,
                        "after": op.action,
                        "model": task.model_name,
                        "provider": task.model_provider,
                    }
                )
            item["note"] = "使用任务原模型方案；重试/恢复可能调用云端并产生费用。"
        if op.kind in {"update_rows", "increment_rows", "delete_rows"} and columns:
            first_key = next(iter(columns))
            for affected in item["affected"]:
                original = json.loads(session.get(DataRowRecord, affected["row_id"]).row_json)
                identifier = original.get(first_key)
                if identifier is not None and str(identifier).strip():
                    affected["name"] = f"{columns[first_key].label}：{identifier}"[:160]
        items.append(item)
    if sum(len(i["affected"]) for i in items) > 500:
        raise HTTPException(422, "本次影响超过 500 条记录，请分批处理。")
    return {
        "kind": "operation_plan",
        "title": "、".join(dict.fromkeys(i["label"] for i in items)) + " · "
        + "、".join(dict.fromkeys(i.get("name", "") for i in items))[:80],
        "items": items,
        "guards": guards,
        "auto_allowed": all(
            o.kind in {"update_rows", "increment_rows"}
            for o in body.operations
        ),
        "note": "仅预览；按显示的范围执行。资料变化会使预览失效。",
    }


def validate_guards(session, guards):
    for key, expected in guards.items():
        kind, identifier = key.split(":", 1)
        if guard(session, kind, identifier) != expected:
            raise HTTPException(409, "资料已经变化，请重新生成操作预览；没有覆盖新的修改。")


def fixed_undo_context(session, context, identifier):
    """Restore saved roots even if the edit changed their search/view values.

    Only the original resource grant permits this relaxation. A model asking
    to undo from a different, narrower scope must still satisfy that scope.
    Current write capabilities, selected row IDs and table grants stay intact.
    """
    from document_pipeline_api.services.assistant_memory import scope_identity

    call = session.get(AssistantToolCall, identifier)
    run = session.get(AssistantRun, call.run_id) if call else None
    message = session.get(AssistantMessage, run.message_id) if run else None
    if message and scope_identity(json.loads(message.context_json)) == scope_identity(context.model_dump()):
        update = {"search": ""}
        if context.view_id:
            saved = json.loads(call.result_json)
            expected = saved.get("execution", {}).get("undo_guards", {}).get("view:" + context.view_id)
            if expected is not None:
                if guard(session, "view", context.view_id) != expected:
                    raise HTTPException(409, "原分组定义已变化，请在数据仓库核对后恢复记录。")
                update["view_id"] = None
            # Legacy executions without a saved view definition cannot prove
            # the current group grant is unchanged, so retain that restriction.
        return context.model_copy(update=update)
    return context


def apply_plan(session, context, plan, settings):
    from document_pipeline_api.services.assistant_tools import permitted, require_capability
    from document_pipeline_api.schemas.data_tables import DataRowUpdate
    from document_pipeline_api.services.queue_pause import freeze_new_task_if_paused

    validate_guards(session, plan["guards"])
    if plan.get("undo_of"):
        context = fixed_undo_context(session, context, plan["undo_of"])
    fresh = preview_plan(
        session,
        context,
        (UndoPlan if plan.get("undo_of") else Plan)(title=plan["title"], operations=[item["operation"] for item in plan["items"]]),
    )
    if fresh["guards"] != plan["guards"] or fresh["items"] != plan["items"]:
        raise HTTPException(409, "实际影响范围已变化，请重新生成预览。")
    result, undo, queue = [], [], []
    can_undo = True
    for item in plan["items"]:
        op = Operation.model_validate(item["operation"])
        require_capability(context, CAPABILITY[op.kind])
        if op.table_id:
            permitted(context, "table", op.table_id)
        if op.kind in {"update_rows", "increment_rows"}:
            roots = set(item.get("root_ids", op.row_ids))
            for row in item["affected"]:
                if row["row_id"] not in roots:
                    continue
                current = session.get(DataRowRecord, row["row_id"])
                data_rows.update_data_row(
                    session,
                    op.table_id,
                    current.id,
                    DataRowUpdate(
                        expected_version=current.row_version,
                        changes=row["after"],
                        editor="问知意 / 用户授权",
                    ),
                )
            # One reversal per root. Shared fields continue to use the existing propagation service.
            for row in item["affected"]:
                if row["row_id"] in roots:
                    undo.append(
                        Operation(
                            kind="update_rows",
                            table_id=op.table_id,
                            row_ids=[row["row_id"]],
                            changes=row["before"],
                        ).model_dump(mode="json")
                    )
            result.append({"table_id": op.table_id, "rows": len(item["affected"])})
        elif op.kind == "add_rows":
            created = [
                data_tables.add_row(session, op.table_id, v, "问知意 / 用户授权").id
                for v in op.rows
            ]
            result.append({"table_id": op.table_id, "created_rows": created})
            can_undo = False
        elif op.kind == "delete_rows":
            root_ids = item.get("root_ids", op.row_ids)
            data_tables.delete_rows(session, op.table_id, root_ids)
            result.append({"table_id": op.table_id, "deleted_rows": root_ids})
            can_undo = False
        elif op.kind == "tasks":
            can_undo = False
            for identifier in dict.fromkeys(op.task_ids):
                permitted(context, "task", identifier)
                if op.action == "pause":
                    tasks.pause_task(session, identifier)
                elif op.action == "cancel":
                    tasks.cancel_task(session, identifier)
                elif op.action == "resume":
                    tasks.resume_task(session, settings, identifier)
                else:
                    tasks.retry_task(session, settings, identifier)
                frozen = (
                    freeze_new_task_if_paused(session, identifier)
                    if op.action in {"resume", "retry"}
                    else False
                )
                queue.append({"task_id": identifier, "action": op.action, "frozen": frozen})
                result.append({"task_id": identifier, "action": op.action})
        elif op.kind == "rename_table":
            data_tables.rename_table(session, op.table_id, op.name)
            undo.append(
                Operation(
                    kind="rename_table", table_id=op.table_id, name=item["before"]
                ).model_dump(mode="json")
            )
            result.append({"table_id": op.table_id, "name": op.name})
        elif op.kind == "create_table":
            permitted(context, "template", op.template_id)
            template = templates.get_template(session, op.template_id)
            created = data_tables.create_table(session, op.name, template.id)
            result.append({"table_id": created.id, "name": created.name})
            can_undo = False
        elif op.kind == "add_column":
            column = data_tables.add_custom_column(session, op.table_id, op.name, op.section)
            result.append({"table_id": op.table_id, "column": column.model_dump()})
            can_undo = False
        else:
            views = data_views.create_split_views(
                session, op.table_id, op.field_key or "", by_file=op.by_file
            )
            result.append(
                {"table_id": op.table_id, "views": [v.model_dump(mode="json") for v in views]}
            )
            can_undo = False
    if plan.get("undo_of"):
        original = session.get(AssistantToolCall, plan["undo_of"])
        if original:
            original.status = "undone"
    session.flush()
    # Capture post-execution state; rollback refuses to overwrite subsequent user edits.
    # The inverse restores fixed saved roots. Re-evaluating a dynamic search
    # after changing its matching values can be empty (or select other rows).
    # Keep the row/table guards; the original scope guard was checked before
    # execution and must not invalidate the edit that intentionally changed it.
    undo_guards = {
        key: guard(session, *key.split(":", 1))
        for key in plan["guards"] if not key.startswith("scope:")
    } if can_undo else {}
    return {
        "results": result,
        "queue": queue,
        "undo": list(reversed(undo)) if can_undo else [],
        "undo_guards": undo_guards if can_undo else {},
        "can_undo": can_undo and bool(undo),
    }


def dispatch_queue(settings, execution):
    if not settings.queue_enabled:
        return
    from document_pipeline_api.services.queueing import enqueue_task, revoke_task

    for item in execution.get("queue", []):
        if item["action"] in {"pause", "cancel"}:
            revoke_task(item["task_id"])
        elif not item["frozen"]:
            enqueue_task(item["task_id"])


def preview_undo(session, context, identifier):
    call = session.get(AssistantToolCall, identifier)
    if not call or call.status != "approved":
        raise HTTPException(409, "只能撤销已执行的操作。")
    saved = json.loads(call.result_json)
    execution = saved.get("execution", {})
    if any(op.get("kind") in {"create_template", "update_template", "restore_template"} for op in execution.get("undo", [])):
        raise HTTPException(409, "问知意已移除模板写入，请到模板页面查看版本并恢复。")
    if not execution.get("can_undo"):
        raise HTTPException(409, "这次操作不支持整次撤销，请在原业务页面核对。")
    validate_guards(session, execution["undo_guards"])
    context = fixed_undo_context(session, context, identifier)
    plan = preview_plan(
        session,
        context,
        UndoPlan(title="撤销：" + saved.get("title", "上次操作"), operations=execution["undo"]),
    )
    plan["undo_of"] = identifier
    plan["title"] = "撤销：" + saved.get("title", "上次操作")
    return plan
